docker build -t web-status -f ../../Backend/Services/WebStatus/WebStatus/Dockerfile ../../Backend/
docker build -t identity-provider -f ../../Backend/Services/IdentityProvider/IdentityProvider/Dockerfile ../../Backend/
docker build -t api-gateway -f ../../Backend/Services/ApiGateway/Dockerfile ../../Backend/
docker build -t community-api -f ../../Backend/Services/Community/Community.API/Dockerfile ../../Backend/
docker build -t history-api -f ../../Backend/Services/History/History.API/Dockerfile ../../Backend/
docker build -t library-api -f ../../Backend/Services/Library/Library.API/Dockerfile ../../Backend/
docker build -t search-api -f ../../Backend/Services/Search/Search.API/Dockerfile ../../Backend/
docker build -t storage-api -f ../../Backend/Services/Storage/Storage.API/Dockerfile ../../Backend/
docker build -t subscriptions-api -f ../../Backend/Services/Subscriptions/Subscriptions.API/Dockerfile ../../Backend/
docker build -t users-api -f ../../Backend/Services/Users/Users.API/Dockerfile ../../Backend/
docker build -t video-manager-api -f ../../Backend/Services/VideoManager/VideoManager.API/Dockerfile ../../Backend/
docker build -t video-manager-signalrhub -f ../../Backend/Services/VideoManager/VideoManager.SignalRHub/Dockerfile ../../Backend/
docker build -t video-store-api -f ../../Backend/Services/VideoStore/VideoStore.API/Dockerfile ../../Backend/
docker build -t video-processor-application -f ../../Backend/Services/VideoProcessor/VideoProcessor.Application/Dockerfile ../../Backend/
docker build -t web-client -f ../../Frontend/WebClient/docker-prod/Dockerfile ../../Frontend/WebClient