minikube image load web-status
minikube image load identity-provider
minikube image load api-gateway
minikube image load community-api
minikube image load history-api
minikube image load library-api
minikube image load search-api
minikube image load storage-api
minikube image load subscriptions-api
minikube image load users-api
minikube image load video-manager-api
minikube image load video-manager-signalrhub
minikube image load video-store-api
minikube image load video-processor-application